# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import processor_pb2 as processor__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in processor_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DataProcessorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TransformText = channel.unary_unary(
                '/DataProcessor/TransformText',
                request_serializer=processor__pb2.RawData.SerializeToString,
                response_deserializer=processor__pb2.ProcessedData.FromString,
                _registered_method=True)


class DataProcessorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def TransformText(self, request, context):
        """The Remote Procedure
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DataProcessorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TransformText': grpc.unary_unary_rpc_method_handler(
                    servicer.TransformText,
                    request_deserializer=processor__pb2.RawData.FromString,
                    response_serializer=processor__pb2.ProcessedData.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'DataProcessor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('DataProcessor', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DataProcessor(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def TransformText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DataProcessor/TransformText',
            processor__pb2.RawData.SerializeToString,
            processor__pb2.ProcessedData.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
